dist: trusty

before_install:
  - sudo apt-get -qq update

install:
  - sudo pip install ansible

script:
  - "ansible-playbook -i inventory/hosts.example --syntax-check install-jupyter.yml"
  - "sudo ansible-playbook -i inventory/hosts.example install-jupyter.yml"
