script:
  - "ansible-playbook -i inventory/hosts.example --syntax-check jupyter-notebook/install-jupyter.yml"
  - "sudo ansible-playbook -i inventory/hosts.example jupyter-notebook/install-jupyter.yml"
